name: allianz_dv_snowflake
version: 1.0.0
config-version: 2

profile: allianz

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
docs-paths: ["docs"]
log-path: logs
packages-install-path: dbt_packages
clean-targets: ["target", "dbt_packages", "logs"]

models:
  allianz_dv:
    +materialized: table

    staging:
      +schema: STAGING
      +materialized: view
      +tags: ["staging"]

    dv:
      +schema: DV
      +tags: ["dv"]

      hubs:
        +tags: ["hub"]
      links:
        +tags: ["link"]
      sats:
        +tags: ["sat"]