version: 2
sources:
  - name: raw
    database: ALLIANZ
    schema: RAW
    description: "Raw landed from BigQuery public dataset (thelook_ecommerce)"
    tables:
      - name: users
      - name: products
      - name: order_items
