
-- Run as ACCOUNTADMIN (one-time admin setup)
USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS ALLIANZ;

-- Create a dedicated role for dbt runs (adjust name as you like)
CREATE ROLE IF NOT EXISTS DEV_ROLE;
GRANT ROLE DEV_ROLE TO USER DATACHAIN;  -- replace with your Snowflake username

-- Hand over ownership to SYSADMIN for day-to-day ops (only one owner per object)
GRANT OWNERSHIP ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE  ALLIANZ    TO ROLE SYSADMIN COPY CURRENT GRANTS;

-- Switch to SYSADMIN for normal work
USE ROLE SYSADMIN;
USE DATABASE ALLIANZ;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS DV;

-- Grants for dbt execution role (compute + containers)
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DEV_ROLE;

GRANT USAGE ON DATABASE ALLIANZ TO ROLE DEV_ROLE;
GRANT USAGE ON SCHEMA ALLIANZ.RAW     TO ROLE DEV_ROLE;
GRANT USAGE ON SCHEMA ALLIANZ.STAGING TO ROLE DEV_ROLE;
GRANT USAGE ON SCHEMA ALLIANZ.DV      TO ROLE DEV_ROLE;

-- If dbt will CREATE objects:
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA ALLIANZ.RAW     TO ROLE DEV_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA ALLIANZ.STAGING TO ROLE DEV_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA ALLIANZ.DV      TO ROLE DEV_ROLE;

-- Read access (current + future)
GRANT SELECT ON ALL TABLES    IN SCHEMA ALLIANZ.DV TO ROLE DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ALLIANZ.DV TO ROLE DEV_ROLE;

-- Ensure SYSADMIN is the owner of the schemas (correct ownership command)
GRANT OWNERSHIP ON SCHEMA ALLIANZ.RAW     TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA ALLIANZ.STAGING TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA ALLIANZ.DV      TO ROLE SYSADMIN COPY CURRENT GRANTS;
