CREATE OR REPLACE TABLE ALLIANZ.RAW.USERS (
  USER_ID STRING, FIRST_NAME STRING, LAST_NAME STRING, EMAIL STRING, CREATED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE ALLIANZ.RAW.PRODUCTS (
  PRODUCT_ID STRING, PRODUCT_NAME STRING, CATEGORY STRING, RETAIL_PRICE FLOAT
);

CREATE OR REPLACE TABLE ALLIANZ.RAW.ORDER_ITEMS (
  ORDER_ITEM_ID STRING, ORDER_ID STRING, CUSTOMER_ID STRING, PRODUCT_ID STRING,
  ORDER_TS TIMESTAMP_NTZ, SALE_PRICE FLOAT 
  --,QUANTITY NUMBER
);