version: 2

models:
  - name: hub_customer
    description: "Data Vault Hub for customers (BK=customer_bk)"
    columns:
      - name: h_customer_pk
        tests: [not_null, unique]
      - name: customer_bk
        tests: [not_null]

  - name: hub_product
    description: "Data Vault Hub for products (BK=product_bk)"
    columns:
      - name: h_product_pk
        tests: [not_null, unique]
      - name: product_bk
        tests: [not_null]

  - name: link_customer_product
    description: "Link: customer -> product"
    columns:
      - name: l_customer_product_pk
        tests: [not_null, unique]
      - name: h_customer_pk
        tests:
          - not_null
          - fk_ref:
              arguments:
                parent_model: "{{ ref('hub_customer') }}"
                pk_column: h_customer_pk
      - name: h_product_pk
        tests:
          - not_null
          - fk_ref:
              arguments:
                parent_model: "{{ ref('hub_product') }}"
                pk_column: h_product_pk

  - name: sat_customer
    description: "Satellite with customer attributes"
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [h_customer_pk, load_dts]
    columns:
      - name: h_customer_pk
        tests: [not_null]
      - name: load_dts
        tests: [not_null]
      - name: customer_hashdiff
        tests: [not_null]

  - name: sat_product
    description: "Satellite with product attributes"
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [h_product_pk, load_dts]
    columns:
      - name: h_product_pk
        tests: [not_null]
      - name: load_dts
        tests: [not_null]
      - name: product_hashdiff
        tests: [not_null]